apimServiceName: contosoapi202202-prod
loggers:
    - name: myappinsights-prod
      loggerType: applicationInsights
      description: App insights for production
      resourceId: "/subscriptions/dea5dcc6-1a1a-4694-8e6c-f340da9c7ea1/resourceGroups/apim-appGw-RG/providers/microsoft.insights/components/myappinsights-prod"
      credentials:
        instrumentationKey: "{{Logger-Credentials--6250c23d58d436090c74c060}}"
      isBuffered: true
diagnostics:
   - name: applicationinsights
     verbosity: Error
     loggerId: "/subscriptions/dea5dcc6-1a1a-4694-8e6c-f340da9c7ea1/resourceGroups/apim-appGw-RG/providers/Microsoft.ApiManagement/service/myappinsights-prod/loggers/myappinsights"
